### ISSUE TITLE
Unnecessary runtime dependency on nodejs

### ISSUE THREAD

**Issue by apmorton** [conda-forge/ray-packages-feedstock#174]
### Comment:

AFAIK nodejs is only needed at build time for ray-default - I believe we should drop it from `host` in the next build unless anyone knows otherwise.

Every package we release seems to pick a random version of nodejs to build against, and this is quite annoying in downstream environments.
2.32 -> `nodejs >=22.4.0,<23.0a0`
2.33 -> `nodejs >=20.12.2,<21.0a0`

**Comment by h-vetinari** [comment]
If you need it at build-time, you need it in `host:`; if you want to avoid the run-export, add
```yaml
build:
  ignore_run_exports_from:
    - nodejs
```
to the output that depends on nodejs.

**Comment by mattip** [comment]
Is `ignore_run_exports_from` documented somewhere?

**Comment by apmorton** [comment]
Why do we need it in host? afaik it is _literally_ just being used as a
build tool.

(Install some node modules, run a bundler to build static html content).

That sounds like a build dependency to me, not a host dependency.

**Comment by h-vetinari** [comment]
> Is `ignore_run_exports_from` documented somewhere?

In the conda-build [docs](https://docs.conda.io/projects/conda-build/en/latest/resources/define-metadata.html#export-runtime-requirements)

> Why do we need it in host?

Depends on what's being compiled. If it doesn't compile any platform-dependent code, you might be able to get away with it. Still, in principle, it would be better in host, because it _could_ compile something (even if ray doesn't, in which case overriding the run-export is the right thing to do). Here's an [explanation](https://github.com/conda-forge/staged-recipes/pull/24841#discussion_r1452946898) how to think about build vs. host vs. run. Node is arguably a bit of a special case as [contains](https://conda-metadata-app.streamlit.app/?q=conda-forge%2Flinux-64%2Fnodejs-22.7.0-hf235a45_0.conda) _both_ binaries (to execute during build) as well as headers+libraries (the stuff that needs to be in host).

**Comment by apmorton** [comment]
It doesn't build anything host dependent - it is being used to build the
html frontend static content.

**Comment by timkpaine** [comment]
> It doesn't build anything host dependent - it is being used to build the html frontend static content.

These aren't mutually exclusive, plenty of JS packages require host-dependent tooling in order to (eventually) build host-agnostic frontend code.

**Comment by apmorton** [comment]
> The default is usually the host section, e.g. https://github.com/conda-forge/numpy-feedstock/blob/main/recipe/meta.yaml#L68 as far as I remember, `build` is mostly there for cross-compilation, when your build tool has to match your host but not your target.

Wow, that is wild to me - I cannot fathom a reason you would want or need ninja installed for the _host_ architecture (which is effectively what would happen in the numpy recipe when cross compiling - you'll get it for both the host and build arch).

**Comment by timkpaine** [comment]
Of course, what its used for and how its supposed to be work [might not match](https://github.com/conda-forge/conda-forge.github.io/issues/1841#issuecomment-1581381250)

**Comment by apmorton** [comment]
Closing as this was done a while ago and nothing seems to have broken
